// @ts-check
import { defineConfig } from 'astro/config';
import cloudflare from '@astrojs/cloudflare';
import tailwindcss from '@tailwindcss/vite';

const SITE = 'https://cihatata.dev';

export default defineConfig({
  site: SITE,
  output: 'server',
  trailingSlash: 'never',
  adapter: cloudflare({
    imageService: 'compile',
    platformProxy: { enabled: true },
  }),
  // Nothing on the site is per-visitor state, so skipping sessions keeps the
  // worker free of a KV binding it would never read.
  session: false,
  i18n: {
    locales: ['en', 'tr'],
    defaultLocale: 'en',
    routing: {
      prefixDefaultLocale: false,
    },
  },
  // The sitemap is generated by src/pages/sitemap.xml.ts instead of
  // @astrojs/sitemap, which can only see prerendered routes and would miss
  // every server-rendered post and tag page.
  markdown: {
    shikiConfig: {
      themes: { light: 'github-light', dark: 'github-dark' },
      wrap: true,
    },
  },
  vite: {
    plugins: [tailwindcss()],
  },
});
